//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a Partner account. If there are none leave this file empty.

== Predeployment steps

Perform the following steps to create a version of the {partner-product-short-name} container that works with AWS Batch and then host it on Amazon ECR. 

. Create an Amazon ECR repository on AWS to hold the Docker image on AWS. Make note of the Uniform Resource Identifier (URI) of the repository. 
. Install {partner-product-short-name} on a machine that has access to sudo.
. Request a https://www.nvidia.com/en-us/clara/genomics/parabricks-free-trial/[Parabricks trial license^].
. Using the installer tarball, run: 

----
sudo parabricks/installer.py
----

[start=5]
. To verify the installation, run:
----
pbrun –help
----

[start=6]
. Modify the Docker image so that it's compatible with AWS Batch. Specifically, create the Docker file that builds on top of the Docker image that the installer just created. Don’t forget to add your {partner-product-short-name} version number in line 1. 

[start=7]
. To view the current Docker file, run:
----
$ cat Dockerfile
----
[start=8]
. To edit and verify your Docker file, run:
----
$ vi Dockerfile
----

----
# Add your Parabricks version number
ARG version=”<INSERT VERSION NUMBER HERE Ex. 3.6.1-1>”
FROM parabricks/release:$version

# Untar this folder to access the pbrun executable
RUN cd /parabricks && tar xzvf release-$version.tar.gz

# Add the pbrun executable to the path
ENV PATH="/parabricks/release-$version:${PATH}"

# Remove the entry point from the container to work with AWS Batch
ENTRYPOINT [""]
----

[start=9]
. To build the Docker image and tag it with the URI for the ECR repository, run:
----
$ docker build -t <URI for your ECR repository> .
----

[start=10]
. To upload the image to Amazon ECR, run:

----
aws ecr get-login-password --region us-west-2 \| docker login --username AWS --password-stdin <URI for your ECR repository>
----