//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a Partner account. If there are none leave this file empty.

== Predeployment steps

Create a version of the {partner-product-short-name} container that works with AWS Batch and then host it on Amazon ECR. Perform the following steps.

. Create an Amazon ECR repository on AWS to hold the Docker image on AWS. Make note of the Uniform Resource Identifier (URI) of the repository. 
. Install {partner-product-short-name} on a machine that has access to Sudo.
. Request a https://www.nvidia.com/en-us/clara/genomics/parabricks-free-trial/[Parabricks trial license^].
. Using the installer tarball, run: 

----
sudo parabricks/installer.py
----

. To verify the installation, run:
----
pbrun –help
----

. Modify the Docker image so that it's compatible with AWS Batch.

- Create this Dockerfile which builds on top of the Docker image the installer just created
- Note: Don’t forget to add your Parabricks version number in line 1

View current "DockerFile":
----
$ cat Dockerfile
----
Edit your "DockerFile" and verify the following:
----
$ vi Dockerfile
----

----
# Add your Parabricks version number
ARG version=”<INSERT VERSION NUMBER HERE Ex. 3.6.1-1>”
FROM parabricks/release:$version

# Untar this folder to access the pbrun executable
RUN cd /parabricks && tar xzvf release-$version.tar.gz

# Add the pbrun executable to the path
ENV PATH="/parabricks/release-$version:${PATH}"

# Remove the entrypoint from the container to work with AWS Batch
ENTRYPOINT [""]
----
Now build the Docker image and tag it with the URI for the ECR repository
----
$ docker build -t <URI for your ECR repository> .
----

Step 3: Upload this image to ECR

----
aws ecr get-login-password --region us-west-2 \| docker login --username AWS --password-stdin <URI for your ECR repository>
----