//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a Partner account. If there are none leave this file empty.

== Predeployment steps

We need to create a version of the Parabricks container will work with AWS Batch and host it on AWS ECR:

Step 0: Create an ECR repository on AWS to hold this docker image on AWS

-Note: Keep the URI of his repo handy

Step 1: Install Parabricks normally onto any machine where you have sudo access

- Request a https://www.nvidia.com/en-us/clara/genomics/parabricks-free-trial/[Parabricks trial license]

Once you have the installer tarball you can run:
----
sudo parabricks/installer.py
----

Verify your installation by running:
----
pbrun –help
----

Step 2: Modify the Docker image to be compatible with AWS Batch

- Create this Dockerfile which builds on top of the Docker image the installer just created
- Note: Don’t forget to add your Parabricks version number in line 1

View current "DockerFile":
----
$ cat Dockerfile
----
Edit your "DockerFile" and verify the following:
----
$ vi Dockerfile
----

----
# Add your Parabricks version number
ARG version=”<INSERT VERSION NUMBER HERE Ex. 3.6.1-1>”
FROM parabricks/release:$version

# Untar this folder to access the pbrun executable
RUN cd /parabricks && tar xzvf release-$version.tar.gz

# Add the pbrun executable to the path
ENV PATH="/parabricks/release-$version:${PATH}"

# Remove the entrypoint from the container to work with AWS Batch
ENTRYPOINT [""]
----
Now build the Docker image and tag it with the URI for the ECR repository
----
$ docker build -t <URI for your ECR repository> .
----

Step 3: Upload this image to ECR

----
aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin <URI for your ECR repository>
----